services:
  frontend:
    build: .
    working_dir: /app/frontend
    command: npx nuxt dev --host 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.nuxt
      - /app/frontend/.output
    env_file:
      - ./frontend/.env
    environment:
      - HOST=0.0.0.0

  studio:
    build: .
    working_dir: /app/studio
    command: npx sanity dev --host 0.0.0.0
    ports:
      - "3333:3333"
    volumes:
      - ./studio:/app/studio
      - /app/studio/node_modules
      - /app/studio/.sanity
      - /app/studio/dist
    env_file:
      - ./studio/.env
    environment:
      - HOST=0.0.0.0
